# Generated by the VisualDSP++ IDDE

# Note:  Any changes made to this Makefile will be lost the next time the
# matching project file is loaded into the IDDE.  If you wish to preserve
# changes, rename this file and run it externally to the IDDE.

# The syntax of this Makefile is such that GNU Make v3.77 or higher is
# required.

# The current working directory should be the directory in which this
# Makefile resides.

# Supported targets:
#     test_ext_Debug
#     test_ext_Debug_clean

# Define this variable if you wish to run this Makefile on a host
# other than the host that created it and VisualDSP++ may be installed
# in a different directory.

ADI_DSP=C:\Program Files (x86)\Analog Devices\VisualDSP 3.5 16-Bit

ifndef ADI_DSP_MAKE
ADI_DSP_MAKE=C:/Program\ Files\ (x86)/Analog\ Devices/VisualDSP\ 3.5\ 16-Bit
endif

# $VDSP is a gmake-friendly version of ADI_DIR

empty:=
space:= $(empty) $(empty)
VDSP_INTERMEDIATE=$(subst \,/,$(ADI_DSP))
VDSP=$(subst $(space),\$(space),$(VDSP_INTERMEDIATE))

# Define the command to use to delete files (which is different on Win95/98
# and Windows NT/2000)

ifeq ($(OS),Windows_NT)
RM=cmd /C del /F /Q
else
RM=command /C del
endif

#
# Begin "test_ext_Debug" configuration
#

ifeq ($(MAKECMDGOALS),test_ext_Debug)

test_ext_Debug : ./Debug/test_ext.dxe 

./Debug/test_ext.doj :./def2181.h ./test_ext.asm 
	$(VDSP)/easm218x.exe .\test_ext.asm -proc ADSP-2181 -g -o .\Debug\test_ext.doj -MM

./Debug/test_ext.dxe :./ADSP-2181.ldf ./Debug/test_ext.doj 
	$(VDSP)/cc218x.exe .\Debug\test_ext.doj -T .\ADSP-2181.ldf -L .\Debug -flags-link -od,.\Debug -o .\Debug\test_ext.dxe -proc ADSP-2181 -flags-link -MM

endif

ifeq ($(MAKECMDGOALS),test_ext_Debug_clean)

test_ext_Debug_clean:
	$(RM) ".\Debug\test_ext.doj"
	$(RM) ".\Debug\test_ext.dxe"
	$(RM) ".\Debug\*.ipa"
	$(RM) ".\Debug\*.opa"
	$(RM) ".\Debug\*.ti"

endif


